import {
  BellRing,
  Box,
  Car,
  CheckCircle2,
  CircleDollarSign,
  ClipboardList,
  CreditCard,
  FileText,
  Hourglass,
  PackageCheck,
  ReceiptText,
  RefreshCcw,
  RotateCcw,
  ShoppingCart,
  Sparkles,
  Truck,
  WalletCards,
  XCircle,
} from "lucide-react"

import type { FeatureSection } from "@/lib/feature-types"

export const whatsappFeatureSections: FeatureSection[] = [
  {
    title: "Store & Order Automation",
    description:
      "Keep customers informed at every stage of their order journey.",
    items: [
      {
        id: "order-confirmation",
        title: "Order confirmation messages",
        description: "Send an instant WhatsApp confirmation when an order is placed.",
        icon: CheckCircle2,
        shopifyTopic: "orders/create",
      },
      {
        id: "payment-confirmation",
        title: "Payment confirmation",
        description: "Confirm successful payments and put customers at ease.",
        icon: WalletCards,
        shopifyTopic: "orders/paid",
      },
      {
        id: "order-processing",
        title: "Order processing updates",
        description: "Notify customers when their order moves into processing.",
        icon: ClipboardList,
        shopifyTopic: "orders/updated",
      },
      {
        id: "order-shipped",
        title: "Order shipped notification",
        description: "Share tracking details as soon as an order ships.",
        icon: Truck,
        shopifyTopic: "fulfillments/create",
      },
      {
        id: "out-for-delivery",
        title: "Out for delivery",
        description: "Let customers know their package is on the way.",
        icon: Car,
        shopifyTopic: "fulfillments/update",
      },
      {
        id: "delivered-confirmation",
        title: "Delivered confirmation",
        description: "Confirm delivery and encourage feedback.",
        icon: PackageCheck,
        shopifyTopic: "fulfillments/update",
      },
      {
        id: "order-cancelled",
        title: "Order cancelled notification",
        description: "Keep customers informed if an order is cancelled.",
        icon: XCircle,
        shopifyTopic: "orders/cancelled",
      },
      {
        id: "order-refunded",
        title: "Order refunded notification",
        description: "Notify customers when a refund has been issued.",
        icon: ReceiptText,
        shopifyTopic: "refunds/create",
      },
      {
        id: "invoice-sharing",
        title: "Invoice/PDF sharing",
        description: "Automatically share invoices and PDFs over WhatsApp.",
        icon: FileText,
        shopifyTopic: "orders/create",
      },
      {
        id: "cod-confirmation",
        title: "COD order confirmation",
        description: "Confirm cash-on-delivery orders with clear details.",
        icon: CircleDollarSign,
        shopifyTopic: "orders/create",
      },
      {
        id: "return-updates",
        title: "Return request updates",
        description: "Keep customers updated on return request status.",
        icon: RotateCcw,
        shopifyTopic: "orders/updated",
      },
      {
        id: "exchange-updates",
        title: "Exchange status updates",
        description: "Share exchange progress from request to resolution.",
        icon: RefreshCcw,
        shopifyTopic: "orders/updated",
      },
    ],
  },
  {
    title: "Abandoned Cart Recovery",
    description:
      "Recover lost sales with timely WhatsApp reminders and one-click checkout.",
    items: [
      {
        id: "cart-reminder",
        title: "Instant abandoned cart reminder",
        description: "Send a reminder as soon as a cart is abandoned.",
        icon: BellRing,
        tag: "Popular",
        shopifyTopic: "checkouts/create",
      },
      {
        id: "follow-up-reminders",
        title: "Multiple follow-up reminders",
        description: "Schedule a sequence of reminders to win customers back.",
        icon: Hourglass,
        shopifyTopic: "checkouts/create",
      },
      {
        id: "one-click-checkout",
        title: "Recover cart with one-click checkout link",
        description: "Let customers resume checkout with a single tap.",
        icon: ShoppingCart,
        shopifyTopic: "checkouts/create",
      },
      {
        id: "discount-coupon",
        title: "Offer discount coupon automatically",
        description: "Incentivize recovery with automatic discount codes.",
        icon: WalletCards,
        shopifyTopic: "checkouts/create",
      },
      {
        id: "ai-recovery",
        title: "AI-generated recovery messages",
        description: "Use AI to write personalized recovery messages.",
        icon: Sparkles,
        tag: "AI",
        shopifyTopic: "checkouts/create",
      },
      {
        id: "abandoned-checkout",
        title: "Recover abandoned checkout",
        description: "Target customers who reach checkout but do not complete.",
        icon: ShoppingCart,
        shopifyTopic: "checkouts/update",
      },
      {
        id: "browse-recovery",
        title: "Recover abandoned browse sessions",
        description: "Re-engage shoppers who browsed but left without adding to cart.",
        icon: Sparkles,
        shopifyTopic: "checkouts/create",
      },
      {
        id: "cart-analytics",
        title: "Cart recovery analytics",
        description: "Track recovery rate, revenue, and campaign performance.",
        icon: ClipboardList,
      },
    ],
  },
  {
    title: "Payment Automation",
    description:
      "Collect payments faster with automated reminders and payment links.",
    items: [
      {
        id: "payment-reminder",
        title: "Payment reminder",
        description: "Remind customers about upcoming or due payments.",
        icon: BellRing,
      },
      {
        id: "failed-payment",
        title: "Failed payment reminder",
        description: "Alert customers when a payment fails.",
        icon: XCircle,
      },
      {
        id: "subscription-renewal",
        title: "Subscription renewal reminder",
        description: "Notify subscribers before their renewal date.",
        icon: RefreshCcw,
      },
      {
        id: "invoice-reminder",
        title: "Invoice reminder",
        description: "Send timely reminders for unpaid invoices.",
        icon: FileText,
      },
      {
        id: "payment-received",
        title: "Payment received confirmation",
        description: "Confirm that a payment has been received.",
        icon: CheckCircle2,
      },
      {
        id: "payment-link",
        title: "UPI/Stripe/Razorpay payment link",
        description: "Share a secure payment link for quick checkout.",
        icon: CreditCard,
      },
      {
        id: "payment-receipt",
        title: "Auto-send payment receipt",
        description: "Deliver receipts automatically after every payment.",
        icon: ReceiptText,
      },
    ],
  },
  {
    title: "Shipping & Delivery",
    description:
      "Reduce support tickets with proactive delivery notifications.",
    items: [
      {
        id: "live-tracking",
        title: "Live shipment tracking",
        description: "Share real-time tracking updates with customers.",
        icon: Truck,
      },
      {
        id: "delivery-eta",
        title: "Delivery ETA updates",
        description: "Keep customers updated on expected delivery times.",
        icon: Hourglass,
      },
      {
        id: "delay-notifications",
        title: "Delay notifications",
        description: "Alert customers promptly about delivery delays.",
        icon: BellRing,
      },
      {
        id: "pickup-notifications",
        title: "Pickup notifications",
        description: "Notify customers when their order is ready for pickup.",
        icon: Box,
      },
      {
        id: "delivery-confirmation",
        title: "Delivery confirmation",
        description: "Confirm successful delivery with customers.",
        icon: PackageCheck,
      },
      {
        id: "delivery-feedback",
        title: "Ask for delivery feedback",
        description: "Request feedback after a successful delivery.",
        icon: ClipboardList,
      },
    ],
  },
]
